"""
Celery worker for asynchronous animation frame generation.
Integrates with Telekinesis multi-agent system.
"""
import os
from celery import Celery
from pathlib import Path
import shutil

from app.telekinesis.graph import build_telekinesis_graph

# Initialize Celery
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
celery_app = Celery(
    "vizier_worker",
    broker=REDIS_URL,
    backend=REDIS_URL
)

# Configure Celery
celery_app.conf.update(
    task_serializer="json",
    accept_content=["json"],
    result_serializer="json",
    timezone="UTC",
    enable_utc=True,
    task_track_started=True,
    task_time_limit=600,  # 10 minutes max per task
    task_soft_time_limit=540,  # 9 minutes soft limit
)

# Import job store and update function
from app.job_store import job_store, update_job_status


@celery_app.task(bind=True, name="app.workers.celery_worker.generate_frames_task")
def generate_frames_task(self, job_id: str, frame1_path: str, frame2_path: str, instruction: str):
    """
    Async task to generate animation frames using Telekinesis agent loop.

    Args:
        job_id: Unique job identifier
        frame1_path: Path to first keyframe
        frame2_path: Path to second keyframe
        instruction: Natural language animation instruction

    Updates job status throughout execution.
    """
    try:
        # Update status: analyzing
        update_job_status(
            job_id=job_id,
            status="processing",
            progress=10,
            stage="analyzing"
        )

        # Build Telekinesis graph
        graph = build_telekinesis_graph()

        # Create initial state
        initial_state = {
            "keyframe1": frame1_path,
            "keyframe2": frame2_path,
            "instruction": instruction,
            "iteration_count": 0,
            "messages": []
        }

        # Execute agent loop with progress updates
        final_state = None
        agent_progress_map = {
            "analyze": 20,
            "identify_principles": 35,
            "plan_frames": 50,
            "generate_frames": 70,
            "validate_quality": 85,
            "refine_frames": 90
        }

        for state_update in graph.stream(initial_state):
            # Get current agent from state update
            current_agent = list(state_update.keys())[0]
            final_state = state_update[current_agent]

            # Update progress based on agent
            progress = agent_progress_map.get(current_agent, 50)
            stage_name = current_agent.replace("_", " ").title()

            update_job_status(
                job_id=job_id,
                status="processing",
                progress=progress,
                stage=stage_name
            )

        # Get generated frames from final state
        frames = final_state.get("refined_frames") or final_state.get("frames", [])

        if not frames:
            raise ValueError("No frames generated by Telekinesis pipeline")

        # Create output directory
        output_dir = Path("outputs") / job_id
        output_dir.mkdir(parents=True, exist_ok=True)

        # Copy frames to output directory with standardized names
        frame_names = []
        for i, frame_path in enumerate(frames):
            frame_name = f"frame_{i+1:03d}.png"
            dest_path = output_dir / frame_name
            shutil.copy(frame_path, dest_path)
            frame_names.append(frame_name)

        # Extract animation parameters if available
        params = final_state.get("plan", {}).get("params")

        # Update status: complete
        update_job_status(
            job_id=job_id,
            status="complete",
            progress=100,
            stage="complete",
            frames=frame_names,
            params=params
        )

        return {
            "job_id": job_id,
            "status": "complete",
            "frames": frame_names
        }

    except Exception as e:
        # Update status: failed
        update_job_status(
            job_id=job_id,
            status="failed",
            progress=0,
            stage=None,
            error=str(e)
        )

        # Re-raise exception for Celery
        raise e
